version: '3'
services:
    server1:
        image: server2
        ports:
            - "443:443"
        networks:
            - mynetwork
    proxy:
        image: proxy
        ports:
          - "80:80"
        networks:
            - mynetwork
networks:
  default:
    external:
      name: mynetwork
